tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
    env:
      DATABASE_URL: postgresql://gitpod@localhost/dailychecks
  - command: npx prisma studio
    env:
      DATABASE_URL: postgresql://gitpod@localhost/dailychecks
ports:
  - port: 3000
    onOpen: open-browser
    
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - svelte.svelte-vscode
    - prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
