tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
    
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
